### ISSUE TITLE
onResult called multiple times

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#11]
sometimes when I scan a barcode on iOS, the phone vibrates ~5-10 times and then i get the below error ~5-10 times

I have cancelOnResult set to true (I made sure in the debugger, in AnylineSDKPlugin), though this setting doesn't seem to propagate to AnylineBarcodeScanViewController

On a side note: if cancelOnResult is false, then this error will happen too, so I think in that case events should be used instead of callbacks, and a "stop" method introduced. What do you think?

![img_2218](https://cloud.githubusercontent.com/assets/83948/22175480/6394c7d2-dfc3-11e6-8b0b-2f7ecff7d19e.jpg)

**Comment by JonasLaux** [comment]
Hey,
yes, good call. We did try to implement an third callback 'onCancel', which would be called on circumstances like this. This didn't workout, because react native throwing an error something like:
Argument ... should be a function which was thrown everytime we called the function with more then 4 parameters.
Events would be a good solution!

**Comment by JonasLaux** [comment]
Hey, this is fixed by Version 3.12

**Comment by shubhnik** [comment]
@JonasLaux  The issue still exists in version 3.12, i am getting multiple calls to onResult.

**Comment by JonasLaux** [comment]
Hi @shubhnik,
what exactly is crashing? Can you provide additional information? What is you'r Environment? Is it in the Barcode Module? Which configuration do you use?

**Comment by shubhnik** [comment]
@JonasLaux It isn't crashing though,I tried OCR and Barcode module and onResult was invoked multiple times on both, I was trying it on ios.

**Comment by JonasLaux** [comment]
do you have cancelOnResult set to false in your Config?

**Comment by shubhnik** [comment]
@JonasLaux for barcode config it is true, for OCR config it is false.

**Comment by JonasLaux** [comment]
Hi,
sorry for not getting back on you. Is this still an issue? In our manual testings, this didn't happen anymore in the last few release.

**Comment by mvayngrib** [comment]
@JonasLaux don't have time to test at the moment, but will let you know when I do, thanks :)

**Comment by Anuskhan** [comment]
E:\data\react-native projects\azad_health\android\app\src\main\java\com\azad_health\MainApplication.java:6: error: package com.anyline.reactnative does not exist
import com.anyline.reactnative.AnylinePackage;
                              ^

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
